# Site settings
title: Keivan & Shannon
email: hello@keivanandshannon.com
url: keivanandshannon.com
description: "Keivan & Shannon"
google_analytics: G-1X3KPT2R01

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-light: '#FDFDFD'
  primary-dark: '#38302D'
  primary-accent: '#143470'

# Footer settings
footer: Keivan Zolfaghari & Shannon Lin

logo: /img/favicons/favicon-32x32.png
cover: /img/screenshot.png

# Build settings
markdown: kramdown
permalink: pretty

include:
  - '_pages'

exclude:
  - 'README.md'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

